PRJ/Models/Movie.cs
using System;
using System.Collections.Generic;

namespace Project_Movie_Group6.Models
{
    public partial class Movie
    {
        public Movie()
        {
            Rates = new HashSet<Rate>();
        }

        public int MovieId { get; set; }
        public string? Title { get; set; }
        public int? Year { get; set; }
        public string? Image { get; set; }
        public string? Description { get; set; }
        public int? GenreId { get; set; }
        public bool? IsActive { get; set; }

        public virtual Genre? Genre { get; set; }
        public virtual ICollection<Rate> Rates { get; set; }
    }
}

PRJ/Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using Project_Movie_Group6.Helpper;
using Project_Movie_Group6.Models;

namespace Project_Movie_Group6.Controllers
{
    public class MovieController : Controller
    {

        private readonly CenimaDBContext _context;

        public MovieController(CenimaDBContext context)
        {
            _context = context;
        }
        // GET: MovieController
        public ActionResult Index(int id)
        {
            if (id > 0)
            {
                var movies = _context.Movies.Include(g => g.Genre).Where(m => m.MovieId == id).FirstOrDefault();
                ViewData["movie"] = movies;
                var rates = _context.Rates.Include(p => p.Person).Where(m => m.MovieId == id).OrderByDescending(r => r.Time).ToList();
                
                var account = _context.Persons.ToList();
                var avg = rates.Average(a => a.NumericRating);
                ViewData["avg"] = avg;
                ViewData["rate"] = rates;

            }
            return View();
        }

        public ActionResult CreateRate(int id)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (id > 0)
                {
                    int check = id;
                    var movies = _context.Movies.Include(g => g.Genre).Where(m => m.MovieId == id).FirstOrDefault();
                    ViewData["movie"] = movies;
                    var rates1 = _context.Rates.ToList();

                    var rates = _context.Rates.Include(p => p.Person).Where(m => m.MovieId == id).OrderByDescending(r => r.Time).ToList();
                    LoginModel p = HttpContext.Session.GetObjectFromJson<LoginModel>("account");

                    Person person = _context.Persons.FirstOrDefault(x => x.Email == p.Email);

                    //(LoginModel)JsonSerializer.Deserialize<LoginModel>(Context.Session.GetString("admin"))


                    var avg = rates.Average(a => a.NumericRating);
                    ViewData["rateCreateRate"] = rates1;
                    ViewData["rates"] = rates;
                    ViewData["avg"] = avg;
                    ViewData["person"] = person;

                }

                return View();
            } else
            {
                return RedirectToAction("Index", "Home");

            }
        }


        [HttpPost]
        public IActionResult Update(Rate rate)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (rate.Comment != null && rate.NumericRating != null)
                {
                    var r = _context.Rates.Where(p => p.PersonId == rate.PersonId && p.MovieId == rate.MovieId).FirstOrDefault();
                    if (r != null)
                    {
                        r.NumericRating = rate.NumericRating;
                        r.Time = DateTime.Now;
                        r.Comment = rate.Comment;
                        _context.Update(r);
                        _context.SaveChanges();
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            } else
            {
                return RedirectToAction("Index", "Home");
            }
        }



        [HttpPost]
        public IActionResult Add(Rate rate)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (rate.Comment != null && rate.NumericRating != null)
                {
                    rate.Time = DateTime.Now;
                    _context.Add(rate);
                    _context.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            } else
            {
                return RedirectToAction("Index", "Home");
            }
        } 
        



    }
}

PRJ/Controllers/PersonLoginController.cs
using Microsoft.AspNetCore.Mvc;

using Project_Movie_Group6.DAO;
using Project_Movie_Group6.Models;

namespace Project_Movie_Group6.Controllers
{
    using Microsoft.AspNetCore.Session;
    using Microsoft.EntityFrameworkCore;
    using Project_Movie_Group6.Helpper;
    using System.Drawing;
    using System.Runtime.Intrinsics.X86;
    using System.Text.Json;

   

    public class PersonLoginController : Controller
    {


        private readonly CenimaDBContext _context;

        public PersonLoginController(CenimaDBContext context)
        {
            _context = context;
        }

        

        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUp(SignUpModel person)
        {
            if (ModelState.IsValid)
            {
                


                var acc = _context.Persons.SingleOrDefault(a => a.Email.Equals(person.Email));
                if (acc != null)
                {
                    ViewData["msg"] = "Email is exsit! !";
                    return View();
                }
                if (person.Password =="" || person.Password.Equals(""))// signupmodel
                {
                    ViewData["msg"] = "Password Not Empty!";
                    return View();
                }


                var pers = new Person
                {
                    Fullname = person.Fullname,
                    Email = person.Email,
                    Gender = person.Gender,
                   
                    Password = person.Password,
                    Type = 2,
                    IsActive = true
                };

                _context.Persons.Add(pers);

                _context.SaveChanges();
               
                HttpContext.Session.SetString("account", JsonSerializer.Serialize(pers));

                //return RedirectToAction("Index", "Home");
                return RedirectToAction("Index", "Home");
                /*return RedirectToPage("index");*/
            }
            else
            {
                return View();
            }
        }

        
    
           
        



        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginModel model)
        {
            if(ModelState.IsValid)// kiểm tr form rỗng 
            {
                var dao = new PersonDAO(_context);
                
                var result = dao.Login(model.Email, model.Password);
                if (result)
                {
                    var person = dao.GetByEmail(model.Email);

                    if (person.IsActive == true)
                    {
                        if (person.Type == 2)
                        {
                            HttpContext.Session.SetString("account", JsonSerializer.Serialize(model));
                            //Person p = HttpContext.Session.GetObjectFromJson<Person>("account");
                            //var personnn = (LoginModel)JsonSerializer.Deserialize<LoginModel>(HttpContext.Session.GetString("account"));
                            //var email = personnn.Email;
                            return RedirectToAction("Index", "Home"); // vào trang home voi action index
                        }
                        else
                        {
                            HttpContext.Session.SetString("admin", JsonSerializer.Serialize(model));
                            
                            return Redirect("~/Admin"); // vào trang home voi action index
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("", "Your Account Is Blocked!!!");
                    }
                        
                    
                }
                else
                {
                    ModelState.AddModelError("", "Login Fail!!!");
                }

            }
            return Login();


        }

        public IActionResult SignOut()
        {
            if (HttpContext.Session.GetString("account") != null) { HttpContext.Session.Remove("account"); }
                
            if (HttpContext.Session.GetString("admin") != null) { HttpContext.Session.Remove("admin"); }
            
            return RedirectToAction("Index", "Home");
        }
    }
}

PRJ/Views/Movie/CreateRate.cshtml
@using Project_Movie_Group6.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model Project_Movie_Group6.Models.Rate

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Movie movies = ViewBag.movie;// luu object phim minh click vao
    List<Rate> rates = ViewBag.rateCreateRate;
    List<Rate> ratesComment = ViewBag.rates;
    Person person = ViewBag.person;
    Rate rateOfAccount = rates.Where(x => x.PersonId == person.PersonId && x.MovieId == movies.MovieId).FirstOrDefault();


    float avg = 0;
    if (ViewBag.avg > 0)
    {
        avg = (float)ViewBag.avg;
    }



}



<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img width="400px" height="800px" src="~/images/MoviesImg/@(movies.Image)" />
            </div>

            <div class="col-md-8">
                <div>
                    <h1>@movies.Title</h1>
                    <div>
                        <a style="font-size: 20px ; font-weight: bold">Thể loại: </a><a>@movies.Genre.Description</a>
                    </div>
                    <div>
                        <a style="font-size: 20px; font-weight: bold">Điểm đánh giá: </a><a>@Math.Round((decimal)avg, 2)</a>
                    </div>
                    <div>
                        <a style="font-size: 20px; font-weight: bold">Mô tả: </a><a>@Html.Raw(movies.Description)</a>
                    </div>

                </div>
                <hr width="100%" size="4px" align="center" color="red" />
                <div>
                    @if(@rateOfAccount == null) {
                    <form asp-action="Add" method="POST">
                        <input asp-for="MovieId" hidden="" value="@movies.MovieId" />
                        <span asp-validation-for="MovieId"></span>

                        <input asp-for="PersonId" hidden="" value="@person.PersonId" />
                        <span asp-validation-for="PersonId"></span>

                        <div>
                            Điểm đánh giá:  <input asp-for="NumericRating" type="number" min="0" max="10"/>
                            <span asp-validation-for="NumericRating"></span>
                                
                        </div>
                        <div>   
                            <p>Bình luận: </p>
                            <textarea asp-for="Comment" style="width: 100%; height: 200px"></textarea>
                            <span asp-validation-for="Comment"></span>
                        </div>
                        <button style="background-color: dodgerblue; color: white; border-radius: 5px; padding: 5px" type="submit">Đánh giá</button>
                    </form>
                    } else {
                    <form asp-action="Update" method="POST">
                        <input asp-for="MovieId" hidden="" value="@movies.MovieId" />
                        <span asp-validation-for="MovieId"></span>

                        <input asp-for="PersonId" hidden="" value="@person.PersonId" />
                        <span asp-validation-for="PersonId"></span>

                        <div>
                                Điểm đánh giá:  <input asp-for="NumericRating" type="number" value="@rateOfAccount.NumericRating" min="0" max="10" step="0.01"/>
                            <span asp-validation-for="NumericRating"></span>
                        </div>
                        <div>
                                
                                <p>Bình luận: </p>
                                <input type="text" asp-for="Comment" style="width: 100%; height: 200px" value="@rateOfAccount.Comment" />
@*                                <textarea asp-for="Comment" style="width: 100%; height: 200px">@rateOfAccount.Comment</textarea>*@                            
                                <span asp-validation-for="Comment"></span>
                        </div>
                        <button style="background-color: dodgerblue; color: white; border-radius: 5px; padding: 5px" type="submit">Đánh giá</button>
                    </form>
                    }

                </div>
                <hr width="100%" size="4px" align="center" color="red" />
                <div>
                    <h2>Bình luận: </h2>
                    @foreach (var item2 in ratesComment)
                    {
                        <div>
                            <a style="font-size: 20px; font-weight: bold">@item2.Person.Fullname : </a>
                            <a>@item2.Comment</a>
                        </div>
                    }
                </div>
            </div>
            }

        </div>
    </div>

</body>

PRJ/Views/Movie/Index.cshtml
@using Project_Movie_Group6.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Movie movies = ViewBag.movie;
    List<Rate> rates = ViewBag.rate;
    Person person = ViewBag.person;
    List<Person> acc = ViewBag.account;
    float avg = 0;
    if(ViewBag.avg > 0)
    {
        avg = (float)ViewBag.avg;
    }
}
<style>
    

    /* The Modal (background) */
    .modal {
        display: none; /* Hidden by default */
        position: fixed; /* Stay in place */
        z-index: 1; /* Sit on top */
        padding-top: 100px; /* Location of the box */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }

    /* Modal Content */
    .modal-content {
        background-color: #fefefe;
        margin: auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
    }

    /* The Close Button */
    .close {
        color: #aaaaaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

        .close:hover,
        .close:focus {
            color: #000;
            text-decoration: none;
            cursor: pointer;
        }
</style>


<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <img width="400px" height="800px" src="~/images/MoviesImg/@(movies.Image)" />
            </div>
            
            <div class="col-md-8">
                <div>
                    <h1>@movies.Title</h1>
                    <div>
                        <a style="font-size: 20px ; font-weight: bold">Thể loại: </a><a>@movies.Genre.Description</a>
                    </div>
                    <div>
                            <a style="font-size: 20px; font-weight: bold">Điểm đánh giá: </a><a>@Math.Round((decimal)avg, 2)</a>
                    </div>
                    <div>
                            <a style="font-size: 20px; font-weight: bold">Mô tả: </a><a>
                            @Html.Raw(movies.Description)
                        </a>
                    </div>
                        @if (Context.Session.GetString("account") != null)
                        {
                        <a asp-action="CreateRate" asp-route-id="@movies.MovieId"><button style="background-color: dodgerblue; color: white; border-radius: 5px">Đánh giá</button></a>
                    }
                    else if (Context.Session.GetString("admin") != null)
                    {
                        <button id="myBtn" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal123" style="background-color: dodgerblue; color: white; border-radius: 5px">Đánh giá</button>

                    }
                    else
                        {
                            <button id="myBtn" type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal" style="background-color: dodgerblue; color: white; border-radius: 5px">Đánh giá</button>
                        }
                </div>
                <hr width="100%" size="4px" align="center" color=" red" />
                <div>
                        <h2>Bình luận: </h2>
                    @foreach (var item2 in rates)
                    {
                        <div>
                            <a style="font-size: 20px; font-weight: bold">@item2.Person.Fullname : </a>
                            <a>@item2.Comment</a>
                        </div>
                    }
                </div>
            </div>
            
            
        </div>
        <div id="myModal" class="modal">

            <!-- Modal content -->
            <div class="modal-content">
                <span class="close">&times;</span>
                <p>Vui lòng <a class="nav-link text-dark" asp-area="" asp-controller="PersonLogin" asp-action="Login" style="display:inline; font-weight: bold; padding: 0px">đăng nhập</a> để bình luận</p>
                <p>Nếu chưa có tài khoản, vui lòng <a class="nav-link text-dark" asp-area="" asp-controller="PersonLogin" asp-action="Login" style="display:inline;font-weight: bold; padding: 0px">đăng ký</a> để tiếp tục</p>
            </div>

        </div>

        <div id="myModal123" class="modal">

            <!-- Modal content -->
            <div class="modal-content">
                <span class="close">&times;</span>
                <p>Bạn đang là admin, nếu muốn đánh giá phim, vui lòng <a class="nav-link text-dark" asp-area="" asp-controller="PersonLogin" asp-action="Login" style="display:inline;font-weight: bold; padding: 0px">đăng ký</a> tài khoản người dùng</p>
            </div>

        </div>

    <script>
        // Get the modal
        var modal = document.getElementById("myModal");

        // Get the button that opens the modal
        var btn = document.getElementById("myBtn");

        // Get the <span> element that closes the modal
        var span = document.getElementsByClassName("close")[0];

        // When the user clicks the button, open the modal
        btn.onclick = function () {
            modal.style.display = "block";
        }

        // When the user clicks on <span> (x), close the modal
        span.onclick = function () {
            modal.style.display = "none";
        }

        // When the user clicks anywhere outside of the modal, close it
        window.onclick = function (event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    </script>
    

</body>