PRJ/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Movie_Group6.Helpper;
using Project_Movie_Group6.Models;

namespace Project_Movie_Group6.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        [Area("Admin")]
        public IActionResult Index()
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("admin") != null)
            {
                return View();
            } else
            {
                return Redirect("~/PersonLogin/Login");
            }
        }
    }
}

PRJ/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Project_Movie_Group6.Helpper;
using Project_Movie_Group6.Models;


namespace Project_Movie_Group6.Controllers
{
    public class HomeController : Controller
    {
        private readonly CenimaDBContext _context;

        public HomeController(CenimaDBContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id, String searchString, int? Page)
        {
            

                List<Movie> Movie = _context.Movies.Include(r => r.Rates).ToList();
                List<Genre> Gender = _context.Genres.ToList();
                List<Rate> rate = _context.Rates.ToList();

                var PageNumber = Page == null || Page <= 0 ? 1 : Page.Value;
                var pageSize = 4;
                var IsCustomers = _context.Movies.AsNoTracking().Include(x => x.Genre).Where(a => a.IsActive ==true).OrderByDescending(x => x.MovieId);
                PagedList<Movie> models = new PagedList<Movie>(IsCustomers, PageNumber, pageSize);


                if (id > 0)
                {
                    IsCustomers = _context.Movies.AsNoTracking().Include(x => x.Genre).Where(g => g.GenreId == id).Where(a => a.IsActive == true).OrderByDescending(x => x.MovieId);
                    models = new PagedList<Movie>(IsCustomers, PageNumber, pageSize);
                    Movie = _context.Movies.Include(r => r.Rates).Where(g => g.GenreId == id).ToList();
                }


                if (!String.IsNullOrEmpty(searchString))
                {
                    string search = Unsign.utf8Convert1(searchString).ToLower();
                    IsCustomers = _context.Movies.AsNoTracking().Include(x => x.Genre).Where(pro => pro.Image.Contains(search)).Where(a => a.IsActive == true).OrderByDescending(x => x.MovieId);
                    models = new PagedList<Movie>(IsCustomers, PageNumber, pageSize);
                    Movie = _context.Movies.Where(pro => pro.Title.Contains(searchString)).ToList();
                }
                ViewData["movie"] = Movie;
                ViewBag.CurrentPage = PageNumber;
                ViewData["gender"] = Gender;
                ViewBag.Rates = rate;
                return View(models);
            
        }
    }
}

PRJ/Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.VisualBasic.Syntax;
using Microsoft.EntityFrameworkCore;
using Project_Movie_Group6.Helpper;
using Project_Movie_Group6.Models;

namespace Project_Movie_Group6.Controllers
{
    public class MovieController : Controller
    {

        private readonly CenimaDBContext _context;

        public MovieController(CenimaDBContext context)
        {
            _context = context;
        }
        // GET: MovieController
        public ActionResult Index(int id)
        {
            if (id > 0)
            {
                var movies = _context.Movies.Include(g => g.Genre).Where(m => m.MovieId == id).FirstOrDefault();
                ViewData["movie"] = movies;
                var rates = _context.Rates.Include(p => p.Person).Where(m => m.MovieId == id).OrderByDescending(r => r.Time).ToList();
                
                var account = _context.Persons.ToList();
                var avg = rates.Average(a => a.NumericRating);
                ViewData["avg"] = avg;
                ViewData["rate"] = rates;

            }
            return View();
        }

        public ActionResult CreateRate(int id)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (id > 0)
                {
                    int check = id;
                    var movies = _context.Movies.Include(g => g.Genre).Where(m => m.MovieId == id).FirstOrDefault();
                    ViewData["movie"] = movies;
                    var rates1 = _context.Rates.ToList();

                    var rates = _context.Rates.Include(p => p.Person).Where(m => m.MovieId == id).OrderByDescending(r => r.Time).ToList();
                    LoginModel p = HttpContext.Session.GetObjectFromJson<LoginModel>("account");

                    Person person = _context.Persons.FirstOrDefault(x => x.Email == p.Email);

                    //(LoginModel)JsonSerializer.Deserialize<LoginModel>(Context.Session.GetString("admin"))


                    var avg = rates.Average(a => a.NumericRating);
                    ViewData["rateCreateRate"] = rates1;
                    ViewData["rates"] = rates;
                    ViewData["avg"] = avg;
                    ViewData["person"] = person;

                }

                return View();
            } else
            {
                return RedirectToAction("Index", "Home");

            }
        }


        [HttpPost]
        public IActionResult Update(Rate rate)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (rate.Comment != null && rate.NumericRating != null)
                {
                    var r = _context.Rates.Where(p => p.PersonId == rate.PersonId && p.MovieId == rate.MovieId).FirstOrDefault();
                    if (r != null)
                    {
                        r.NumericRating = rate.NumericRating;
                        r.Time = DateTime.Now;
                        r.Comment = rate.Comment;
                        _context.Update(r);
                        _context.SaveChanges();
                    }

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            } else
            {
                return RedirectToAction("Index", "Home");
            }
        }



        [HttpPost]
        public IActionResult Add(Rate rate)
        {
            if (HttpContext.Session.GetObjectFromJson<LoginModel>("account") != null)
            {
                if (rate.Comment != null && rate.NumericRating != null)
                {
                    rate.Time = DateTime.Now;
                    _context.Add(rate);
                    _context.SaveChanges();

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }

            } else
            {
                return RedirectToAction("Index", "Home");
            }
        } 
        



    }
}

PRJ/Views/Home/Index.cshtml
@using Project_Movie_Group6.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<Project_Movie_Group6.Models.Movie>
@addTagHelper *, PagedList.Core.Mvc

@{
    int CurrentPage = ViewBag.CurrentPage;
    ViewData["Title"] = "Home Page" + CurrentPage ;

    List<Movie> movies = ViewBag.movie;
    List<Genre> genres = ViewBag.gender;
    List<Rate> averageRate = ViewBag.Rates;

    var result = from r in averageRate
                 group r by r.MovieId into g
                 select new
                 {
                     MovieID = g.Key,
                     Average = g.Average(r => r.NumericRating)
                 };
}

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul style="list-style-type: none">
                    <h3>Thể loại</h3>
                    @foreach (var item in genres)
                    {
                        <li>
                            <a href="/Home/Index/@item.GenreId">@item.Description</a>
                        </li>
                    }
                    
                </ul>
            </div>

            <div class="col-md-10">
                <div class="row">
                    @foreach (var item in Model)
                    {
                        if (item.IsActive == true){
                        <div class="col-md-3" style="border-style: solid; margin: 25px;max-width: 20%; padding: 0px 0px 30px 0px">

                            <img width="100%" height="50%" alt="user" src="~/images/MoviesImg/@(item.Image)">
                            <div style="margin: 20px 0px 10px 20px">
                                <h4><a asp-controller="Movie" asp-action="index" asp-route-id="@item.MovieId" style="text-decoration: none; margin-bottom: 10px">@item.Title</a></h4>
                                <ul style="list-style-type: none; padding: 0px">
                                    <li>Năm: @item.Year</li>
                                    <li>Thể loại : @item.Genre.Description</li>
                                    <li>
                                        Điểm: @foreach (var m in result)
                                        {
                                            if (item.MovieId == m.MovieID)
                                            {
                                                @Math.Round((decimal)m.Average, 2)
                                            }
                                        }

                                    </li>
                                </ul>
                            </div>
                            <a asp-controller="Movie" asp-action="index" asp-route-id="@item.MovieId" style="text-decoration: none; margin-bottom: 10px"><button style="border-radius: 4px;background-color: dodgerblue;color: white; margin-left: 100px; padding: 5px">Đánh giá</button></a>
                        </div>
                    }
                    }
                </div>
            </div>

            <div aria-label="Page navigation example">
                <ul class="pagtination">
                    <pager class="pager-container" list="@Model" asp-controller="Home" asp-action="Index"/>
                </ul>
            </div>


        </div>
    </div>

</body>

PRJ/Views/Home/SearchResult.cshtml
@using Project_Movie_Group6.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Home Page";
    List<Movie> movies = ViewBag.movie;
}


<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <ul style="list-style-type: none">
                    <h3>Thể loại</h3>
                    @foreach (var item in Model)
                    {
                        <li>
                            <a href="/Home/Index/@item.GenreId">@item.Description</a>
                        </li>
                    }

                </ul>
            </div>

            <div class="col-md-10">
                <div class="row">
                    @foreach (var item in movies)
                    {
                        <div class="col-md-3" style="border-style: solid; margin: 25px;max-width: 20%; padding: 0px 0px 30px 0px">

                            <img width="100%" height="50%" alt="user" src="~/images/MoviesImg/@(item.Image)">
                            <div style="margin: 20px 0px 10px 20px">
                                <h4><a asp-controller="Movie" asp-action="index" asp-route-id="@item.MovieId" style="text-decoration: none; margin-bottom: 10px">@item.Title</a></h4>
                                <ul style="list-style-type: none; padding: 0px">
                                    <li>Năm: @item.Year</li>
                                    <li>Thể loại: @item.Genre.Description</li>
                                    <li>Điểm: @item.Genre</li>
                                </ul>
                            </div>
                            <a asp-controller="Movie" asp-action="index" asp-route-id="@item.MovieId" style="text-decoration: none; margin-bottom: 10px"><button style="border-radius: 4px;background-color: dodgerblue;color: white; margin-left: 100px; padding: 5px">Đánh giá</button></a>
                        </div>
                    }

                </div>
            </div>
        </div>
    </div>

</body>
<footer>
</footer>

PRJ/Views/Home/Testing.cshtml
@model IEnumerable<Project_Movie_Group6.Models.Movie>
@using Project_Movie_Group6.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Home Page";
    List<Movie> movies = ViewBag.movie;
}
<h1>List of Movies</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Year</th>
            <th>Genre</th>
            <th>Average Rating</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var movie in ViewBag.Rate)
        {
            <tr>
                <td>@movie.Title </td>
                <td>@movie.Year</td>
                <td>@movie.Genre.Description</td>
                <td></td>
            </tr>
        }
    </tbody>
</table>